name: Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install poetry
        run: |
          pip install --user pipx
          pipx ensurepath
          pipx install poetry
      - name: Poetry Version
        run: |
          poetry --version
      - name: Poetry Install Dependencies
        run: |
          poetry install --no-interaction
      - name: Lint with Ruff
        run: |
          poetry run ruff check . --config pyproject.toml --output-format=github
      - name: Format with Ruff
        run: |
          poetry run ruff format . --config pyproject.toml --check --diff
      - name: Test with pytest
        run: |
          poetry run pytest .
